authapp/urls.py
from django.urls import path

from authapp import views


app_name = 'authapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    #path('login/', views.login, name='login'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admins'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatar', blank=True)
    age = models.PositiveSmallIntegerField(blank=True, null=True)

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'age','avatar')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите адрес эл. почты'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Введите пароль еще раз'
        self.fields['age'].widget.attrs['placeholder'] = 'Введите возраст'
        self.fields['avatar'].widget.attrs['placeholder'] = 'Загрузите аватар'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserProfileForm(UserChangeForm):
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'age','avatar')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.views import LoginView

from basketapp.models import Basket
from authapp.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from authapp.models import User



class UserLoginView(LoginView):
    template_name = 'authapp/login.html'
    form_class = UserLoginForm


class UserCreateView(CreateView):
    model = User
    template_name = 'authapp/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('auth:login')

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))

class UserProfileView(UpdateView):
    model = User
    template_name = 'authapp/profile.html'
    form_class = UserProfileForm

    def get_success_url(self):
        self.success_url = reverse_lazy('auth:profile', args=[self.kwargs['pk']])
        return str(self.success_url)




# @login_required
# def profile(request):
#     if request.method == 'POST':
#         form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('auth:profile'))
#     else:
#         form = UserProfileForm(instance=request.user)
#     context = {'head': 'GeekShop - Профиль',
#                'form': form,
#                'baskets': Basket.objects.filter(user=request.user),
#                }
#     return render(request, 'authapp/profile.html', context)

authapp/templates/authapp/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ head|title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>


<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div {% block div_class %} {% endblock %}>

                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px;">
                                    <strong>Ошибка</strong> {% block errors %} {% endblock %}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% elif messages %}
                                {% for message in messages %}
                                    <div class="alert alert-success alert-dismissible fade show" role="alert"
                                 style="margin-top: 50px; ">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endfor %}

                            {% endif %}
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header">{% block title_auth_register %} {% endblock %}
                                </div>
                                <div class="card-body">
                                    {% block form %} {% endblock %}

                                </div>
                                <div class="card-footer text-center">
                                    {% block link %}{% endblock %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title_auth_register %}
   <h3 class="text-center font-weight-light my-4">Авторизация</h3>
{% endblock %}

{% block div_class %}
    class="col-lg-5"
{% endblock %}

{% block errors %}
    {{ form.non_field_errors}}
{% endblock %}

{% block form %}
    <form action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
            {{ form.password }}
        </div>
        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
            <a class="small" href="#">Забыли пароль?</a>
            <input class="btn btn-primary" type="submit" value="Авторизоваться">
        </div>
    </form>
{% endblock %}

{% block link %}
    <div class="small"><a href="{% url 'auth:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block body_class %}
    class="bg-light"
{% endblock %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>

            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{% if user.avatar %} {{ user.avatar.url }} {% else %} {% static 'no_foto.jpeg' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'authapp:profile' user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                 <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.avatar }}
                                <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">
                                    Выберите изображение
                                </label>
                            </div>
                        </div>
                    </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                        {{ form.age }}
                    </div>
                    <div class="col-lg-6" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
                {% include 'basketapp/basket.html' %}
        </div>

    </div>
</div>
{% endblock %}

{% block footer %} {% endblock %}

{% block basket_scripts %}
    <script src="{% static 'js/basket.js' %}"></script>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title_auth_register %}
    <h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
{% endblock %}

{% block div_class %}
    class="col-lg-7"
{% endblock %}

{% block errors %}
    {{ form.errors}}
{% endblock %}

{% block form %}

    <form action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="col-md-6">
                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                    {{ form.password1 }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password2.id_for_label}}">Подтверждение
                        пароля</label>
                    {{ form.password2 }}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.age.id_for_label}}">Введите возраст</label>
                    {{ form.age }}
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.avatar.id_for_label}}">Загрузите аватар</label>
                    {{ form.avatar }}
                </div>
            </div>

        </div>
        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
        </div>
    </form>
{% endblock %}

{% block link %}
    <div class="small"><a href="{% url 'auth:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
{% endblock %}