adminapp/urls.py
from django.urls import path

from adminapp import views


app_name = 'adminapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('admins-user-read/', views.UserListView.as_view(), name='admins_user_read'),
    path('admins-user-create/', views.UserCreateView.as_view(), name='admins_user_create'),
    path('admins-user-update/<int:pk>/', views.UserUpdateView.as_view(), name='admins_user_update'),
    path('admins-user-delete/<int:pk>/', views.UserDeleteView.as_view(), name='admins_user_delete'),
    path('admins-products-read/', views.ProductsListView.as_view(), name='admin_products_read'),
    path('admins-products-create/', views.ProductsCreateView.as_view(), name='admins_products_create'),
    path('admins-products-update/<int:pk>/', views.ProductsUpdateView.as_view(), name='admins_products_update'),
    path('admins-products-delete/<int:pk>/', views.ProductsDeleteView.as_view(), name='admins_products_delete'),
]

authapp/urls.py
from django.urls import path

from authapp import views


app_name = 'authapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    #path('login/', views.login, name='login'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admins'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, unique=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} категории {self.category.name}'

adminapp/forms.py
from authapp.forms import UserRegisterForm, UserProfileForm
from django import forms
from mainapp.models import Product

class AdminUserRegisterForm(UserRegisterForm):
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(AdminUserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'


class AdminUserProfileForm(UserProfileForm):

    def __init__(self, *args, **kwargs):
        super(AdminUserProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False




class AdminProductsRegisterForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = Product
        fields = ('name', 'image', 'description', 'short_description', 'price', 'quantity', 'category')

    def __init__(self, *args, **kwargs):
        super(AdminProductsRegisterForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название продукта'
        self.fields['image'].widget.attrs['placeholder'] = 'Загрузите изображение продукта'
        self.fields['description'].widget.attrs['placeholder'] = 'Полное описание продукта'
        self.fields['short_description'].widget.attrs['placeholder'] = 'Краткое описание продукта'
        self.fields['price'].widget.attrs['placeholder'] = 'Введите цену'
        self.fields['quantity'].widget.attrs['placeholder'] = 'Укажите кол-во'
        self.fields['category'].widget.attrs['placeholder'] = 'Укажите категорию продукта'

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'


class AdminProductsProfileForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = Product
        fields = ('name', 'image', 'description', 'short_description', 'price', 'quantity', 'category')

    def __init__(self, *args, **kwargs):
        super(AdminProductsProfileForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название продукта'
        self.fields['image'].widget.attrs['placeholder'] = 'Загрузите изображение продукта'
        self.fields['description'].widget.attrs['placeholder'] = 'Полное описание продукта'
        self.fields['short_description'].widget.attrs['placeholder'] = 'Краткое описание продукта'
        self.fields['price'].widget.attrs['placeholder'] = 'Введите цену'
        self.fields['quantity'].widget.attrs['placeholder'] = 'Укажите кол-во'
        self.fields['category'].widget.attrs['placeholder'] = 'Укажите категорию продукта'

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from authapp.models import User
from mainapp.models import Product
from adminapp.forms import AdminUserRegisterForm, AdminUserProfileForm, AdminProductsRegisterForm, AdminProductsProfileForm

@user_passes_test(lambda u: u.is_superuser, login_url='mainapp:products')
def index(request):
    return render(request, 'adminapp/index.html', {'title' : 'Админ'})

# Пользователи

class UserListView(ListView):
    model = User
    template_name = 'adminapp/admins_user_read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'Пользователи'
        return context



# @user_passes_test(lambda u: u.is_superuser)
# def admins_user_read(request):
#     context = {'users': User.objects.all()}
#     return render(request, 'adminapp/admins_user_read.html', context)

class UserCreateView(CreateView):
    model = User
    template_name = 'adminapp/admin-users-create.html'
    form_class = AdminUserRegisterForm
    success_url = reverse_lazy('admins:admins_user_read')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Новый пользователь'
        return context

#
# @user_passes_test(lambda u: u.is_superuser)
# def admins_user_create(request):
#     if request.method == 'POST':
#         form = AdminUserRegisterForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admins:admins_user_read'))
#     else:
#         form = AdminUserRegisterForm()
#     context = {'form': form, }
#     return render(request, 'adminapp/admin-users-create.html', context)

class UserUpdateView(UpdateView):
    model = User
    template_name = 'adminapp/admin_user_update_delete.html'
    form_class = AdminUserProfileForm
    success_url = reverse_lazy('admins:admins_user_read')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование'
        return context

# @user_passes_test(lambda u: u.is_superuser)
# def admins_user_update(request, id=None):
#     user = User.objects.get(id=id)
#     if request.method == 'POST':
#         form = AdminUserProfileForm(data=request.POST, files=request.FILES, instance=user)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admins:admins_user_read'))
#     else:
#         form = AdminUserProfileForm(instance=user)
#     context = {'current_user': user,
#                'form': form,
#                }
#     return render(request, 'adminapp/admin_user_update_delete.html', context)

class UserDeleteView(DeleteView):
    model = User
    template_name = 'adminapp/admin_user_update_delete.html'
    success_url = reverse_lazy('admins:admins_user_read')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserDeleteView, self).dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())



# @user_passes_test(lambda u: u.is_superuser)
# def admins_user_delete(request, id):
#     user = User.objects.get(id=id)
#     user.is_active = False
#     user.save()
#     return HttpResponseRedirect(reverse('admins:admins_user_read'))

# Продукты

class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/admin_products_read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductsListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['title'] = 'Продукты'
        return context


class ProductsCreateView(CreateView):
    model = Product
    template_name = 'adminapp/admin_products_create.html'
    form_class = AdminProductsRegisterForm
    success_url = reverse_lazy('admins:admin_products_read')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductsCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductsCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Добавить продукт'
        return context


class ProductsUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/admins_products_update_delete.html'
    form_class = AdminProductsProfileForm
    success_url = reverse_lazy('admins:admin_products_read')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductsUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductsUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование продукта'
        return context

class ProductsDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/admins_products_update_delete.html'
    success_url = reverse_lazy('admins:admin_products_read')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductsDeleteView, self).dispatch(request, *args, **kwargs)

adminapp/templates/adminapp/admin_products_read.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Продукты</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукты
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Название</th>
                                    <th>Категория</th>
                                    <th>Краткое описание</th>
                                    <th>Цена</th>
                                    <th>Полное описание</th>
                                    <th>Кол-во</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Название</th>
                                    <th>Категория</th>
                                    <th>Краткое описание</th>
                                    <th>Цена</th>
                                    <th>Полное описание</th>
                                    <th>Кол-во</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for product in product_list %}
                                     <tr>
                                        <td><a href="{% url 'admins:admins_products_update' product.id %}" style="color: dodgerblue">{{ product.name }}</a></td>
                                        <td>{{ product.category }}</td>
                                        <td>{{ product.short_description}}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.description}}</td>
                                        <td>{{ product.quantity}}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_products_create' %}">
                            <button class="btn btn-success">Добавить продукт</button>
                        </a>
                    </div>
                </div>
{% endblock %}

adminapp/templates/adminapp/admin_user_update_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
     <h1 class="mt-4">Редактирование пользователя | {{ user }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_user_update' user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.avatar }}
                                    <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">
                                    Выберите изображение
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <form action="{% url 'admins:admins_user_delete' user.id %}" method="post">
                                {% csrf_token %}
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </form>
                        </div>

                    </div>
                </div>
{% endblock %}

adminapp/templates/adminapp/admins_products_update_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
     <h1 class="mt-4">Редактирование товара | {{ product }}</h1>
    <div class="card-body">
        <form action="{% url 'admins:admins_products_update' product.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="form-row">

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                    {{ form.name }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.short_description.id_for_label }}">Краткое описание</label>
                                    {{ form.short_description }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Кол-во</label>
                                    {{ form.quantity }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                    {{ form.category }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                                    {{ form.price }}
                                </div>

                            </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                 {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                    Выберите изображение
                                </label>
                            </div>
                        </div>
                    </div>

                     <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>


                </form>


        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <form action="{% url 'admins:admins_products_delete' product.id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </form>
            </div>
        </div>

    </div>
{% endblock %}

adminapp/templates/adminapp/admins_user_read.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Пользователи</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for user in object_list %}
                                     <tr>
                                        <td><a href="{% url 'admins:admins_user_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                        <td>{{ user.first_name }}</td>
                                        <td>{{ user.last_name }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="text-center">
                                            {% if user.is_staff %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            {% if user.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admins_user_create' %}">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
{% endblock %}

adminapp/templates/adminapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - {{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'main:index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admins_user_read' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="index.html">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_products_read' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
               {% block content %} {% endblock %}
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2020</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>

adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Административная панель</h1>
{% endblock %}