adminapp/urls.py
from django.urls import path

from adminapp import views


app_name = 'adminapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('admins-user-read/', views.UserListView.as_view(), name='admins_user_read'),
    path('admins-user-create/', views.UserCreateView.as_view(), name='admins_user_create'),
    path('admins-user-update/<int:pk>/', views.UserUpdateView.as_view(), name='admins_user_update'),
    path('admins-user-delete/<int:pk>/', views.UserDeleteView.as_view(), name='admins_user_delete'),
    path('admins-products-read/', views.ProductsListView.as_view(), name='admin_products_read'),
    path('admins-products-create/', views.ProductsCreateView.as_view(), name='admins_products_create'),
    path('admins-products-update/<int:pk>/', views.ProductsUpdateView.as_view(), name='admins_products_update'),
    path('admins-products-delete/<int:pk>/', views.ProductsDeleteView.as_view(), name='admins_products_delete'),
]

authapp/urls.py
from django.urls import path

from authapp import views


app_name = 'authapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    #path('login/', views.login, name='login'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('basket-add//<int:product_id>/', basket_add, name='basket_add'),
    path('basket-remove/<int:id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admins'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

from mainapp.views import index, products


app_name = 'mainapp'

urlpatterns = [
    path('', index, name='index'),
    path('products/', products, name='products'),
    path('products/<int:category_id>/', products, name='product'),
    path('products/page/<int:page>/', products, name='product_page'),
    path('products/<int:category_id>/page/<int:page>/', products, name='category_page'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, unique=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} категории {self.category.name}'

mainapp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from mainapp.models import Product, ProductCategory

def index(request):
    context = {
        'head': 'geekShop - главная',
    }
    return render(request, 'mainapp/index.html', context)

def products(request, category_id=None, page=1):
    menu_names = ProductCategory.objects.all()

    if not category_id:
        category_name= ''
        cards = Product.objects.all()
    else:
        category_name = ProductCategory.objects.get(id=category_id)
        cards = Product.objects.filter(category=category_name)
    products_on_page = 2
    paginator = Paginator(cards, products_on_page)
    context = {
        'head': 'geekShop - каталог',
        'menu_names': menu_names,
        'cards': paginator.page(page),
        'category_name': category_name,
    }
    return render(request, 'mainapp/products.html', context)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ head|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body {% block body_class %} {% endblock %}>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div  style="color: #9fcdff; margin-left: 50px">Сегодня: {% now "d M Y  Время: H:i"%}</div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:products' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:profile' user.id %}">{{ user.first_name }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'adminapp:index' %}"><i class="fa fa-users" aria-hidden="true"></i>
    </a>
                        </li>
                        {% endif %}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js'%}" crossorigin="anonymous"></script>

{% block basket_scripts %} {% endblock %}

</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'main:products' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">GeekShop  </h1>
            <div class="list-group">

                {% for menu_name in Pr %}
                    <a href="{% url 'main:product' menu_name.id %}" class="list-group-item">{{ menu_name.name }}</a>
                {% endfor %}

            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for card in cards %}
                    <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="/media/{{ card.image }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ card.name }}</a>
                            </h4>
                            <h5>{{ card.price }}</h5>
                            <p class="card-text">{{ card.short_description }}</p>
                        </div>

                        <div class="card-footer text-center">
                            <a href="{% url 'baskets:basket_add' card.id %}">
                                <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                            </a>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            {% if cards.has_next or cards.has_previous %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not cards.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if cards.has_previous %} {% url 'main:product_page' cards.previous_page_number %} {% endif %}"
                                   tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                                {% for page in cards.paginator.page_range %}
                                    <li class="page-item">
                                        {% if category_name %}
                                            <a class="page-link" href="{% url 'main:category_page' category_name.id page %}">{{ page }}</a>
                                        {% else %}
                                            <a class="page-link" href="{% url 'main:product_page' page %}">{{ page }}</a>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            <li class="page-item {% if not cards.has_next %} disabled {% endif %}">
                                <a class="page-link"
                                   href="{% if cards.has_next %} {% url 'main:product_page' cards.next_page_number %} {% endif %}">Next</a>
                            </li>
                        </ul>
                </nav>
            {% endif %}

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
    </div>
</footer>
{% endblock %}